// generated by gengoos.go using 'go generate'

package runtime

const theGoarch = `s390x`

const goarch_386 = 0
const goarch_amd64 = 0
const goarch_amd64p32 = 0
const goarch_arm = 0
const goarch_arm64 = 0
const goarch_ppc64 = 0
const goarch_ppc64le = 0
const goarch_s390x = 1
